### ISSUE TITLE
[ERROR] 19:15:20 TypeError: main.finally is not a function

### ISSUE THREAD

**Issue by helpsocialbotspy** [Sansossio/instagram-api-test#2]
`$ tsnd ./src --inspect
`

> Using ts-node version 8.10.1, typescript version 3.9.3
> TypeError: main.finally is not a function
>     at Object.<anonymous> (/Users/appion/Documents/Projects/instagram-api-test/src/index.ts:15:13)
>     at Module._compile (module.js:652:30)
>     at Module._compile (/usr/local/lib/node_modules/ts-node-dev/node_modules/source-map-support/source-map-support.js:547:25)
>     at Module.m._compile (/private/var/folders/wb/85mzqshn0gv54rd1jnpgn6tm0000gn/T/ts-node-dev-hook-1706069313774332.js:57:25)
>     at Module._extensions..js (module.js:663:10)
>     at require.extensions.(anonymous function) (/private/var/folders/wb/85mzqshn0gv54rd1jnpgn6tm0000gn/T/ts-node-dev-hook-1706069313774332.js:59:14)
>     at Object.nodeDevHook [as .ts] (/usr/local/lib/node_modules/ts-node-dev/lib/hook.js:61:7)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)
>     at Module.require (module.js:596:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/usr/local/lib/node_modules/ts-node-dev/lib/wrap.js:80:1)
>     at Module._compile (module.js:652:30)
>     at Module._compile (/usr/local/lib/node_modules/ts-node-dev/node_modules/source-map-support/source-map-support.js:547:25)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)
>     at Function.Module.runMain (module.js:693:10)
>     at startup (bootstrap_node.js:188:16)
>     at bootstrap_node.js:609:3
> [ERROR] 19:15:20 TypeError: main.finally is not a function
> 
>

**Comment by helpsocialbotspy** [comment]
Changing:

```
main()
  . finally(() => process.exit());
```
to

```
main()
  .then(() => process.exit());
```
worked
